name: Publish ethereum-ecdsa-verifier to crates.io

on:
  push:
    tags:
      - 'v*.*.*' # Match semantic version tags v1.0.0, v1.2.3, etc.
  workflow_dispatch: # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Rust toolchain
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 3: Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Step 4: Build the project to ensure it compiles
      - name: Build project
        run: cargo build --release

      # Step 5: Run tests to ensure everything works
      - name: Run tests
        run: cargo test

      # Step 6: Login to crates.io
      - name: Login to crates.io
        run: cargo login ${{ secrets.CARGO_TOKEN }}

      # Step 7: Publish the crate
      - name: Publish ethereum-ecdsa-verifier to crates.io
        run: cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}